"""Read-only trading-terminal UI and replay APIs for the frozen shadow."""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from flask import abort, jsonify, Response

import downside_manager_shadow_v1 as shadow
from rl_trade_manager.types import Bar

CATALOG=Path(__file__).resolve().parent/"real_trade_replay_v1/catalog.json"


@lru_cache(maxsize=1)
def _catalog():
    if not CATALOG.exists():
        return {"summary":{},"trades":[],"error":"Replay catalog has not been built"}
    return json.loads(CATALOG.read_text())


def _public(row):
    return {k:v for k,v in row.items() if k!="detail"}


def _live_rows():
    if not shadow.ENABLED:return []
    with shadow._connect() as c:
        return [dict(r) for r in c.execute("""SELECT id,trade_id,source_key,strategy_id,status,
             direction,entry,initial_sl,fixed_tp,quantity,initial_risk,signal_ms,fill_ms,
             current_r,mfe_r,mae_r,manager_probability,recommendation,control_final_r,
             manager_final_r,delta_r,control_exit_reason,manager_exit_reason,state_quality
             FROM downside_shadow_trades ORDER BY id DESC LIMIT 300""")]


def _live_detail(identifier):
    if not shadow.ENABLED:abort(404)
    with shadow._connect() as c:
        stored=c.execute("SELECT * FROM downside_shadow_trades WHERE id=?",(identifier,)).fetchone()
    if stored is None:abort(404)
    row=dict(stored)
    signal=json.loads(row["signal_json"])
    bars=[Bar(*x) for x in json.loads(row["bars_json"])]
    pre=[Bar(*x) for x in json.loads(row["pre_bars_json"])]
    states=json.loads(row["dol_states_json"])
    detail=(shadow.detailed_replay(row,bars,pre,states,quality=row["state_quality"])
            if bars and row["fill_ms"] is not None else None)
    return {"id":row["id"],"trade_id":row["trade_id"],"source_key":row["source_key"],
            "strategy":row["strategy_id"],"session":signal.get("session"),
            "status":row["status"],"side":"LONG" if row["direction"]==1 else "SHORT",
            "entry":row["entry"],"initial_sl":row["initial_sl"],"fixed_tp":row["fixed_tp"],
            "quantity":row["quantity"],"fill_ms":row["fill_ms"],"state_quality":row["state_quality"],
            "actual_broker_usd":None,"control_r":row["control_final_r"],
            "manager_r":row["manager_final_r"],"delta_r":row["delta_r"],"detail":detail}


def register(app):
    app.add_url_rule("/downside-shadow/api/trades","dm_replay_list",
                     lambda:jsonify({"summary":_catalog().get("summary",{}),
                                     "trades":[_public(x) for x in _catalog().get("trades",[])]}))
    def trade(identifier):
        value=next((x for x in _catalog().get("trades",[]) if x["id"]==identifier),None)
        if value is None:abort(404)
        return jsonify(value)
    app.add_url_rule("/downside-shadow/api/trade/<identifier>","dm_replay_one",trade)
    app.add_url_rule("/downside-shadow/api/live","dm_live_list",
                     lambda:jsonify({"status":shadow.status(),"trades":_live_rows()}))
    app.add_url_rule("/downside-shadow/api/live/<int:identifier>","dm_live_one",
                     lambda identifier:jsonify(_live_detail(identifier)))
    for path,endpoint in (("/downside-shadow/trades","dm_history"),
                          ("/downside-shadow/real-replays","dm_real_replays"),
                          ("/downside-shadow/metrics","dm_metrics"),
                          ("/downside-shadow/trade/<identifier>","dm_trade_page")):
        app.add_url_rule(path,endpoint,lambda **_:Response(page(),mimetype="text/html"))


def page():return PAGE


PAGE=r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Downside Manager Shadow</title><style>
:root{color-scheme:dark;--bg:#090e18;--panel:#111b2a;--edge:#233248;--text:#e8f0fa;--muted:#93a7bc;--green:#40d69a;--red:#ff7287;--blue:#69aaff;--amber:#ffc66d}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:13px system-ui,Arial,sans-serif}header{padding:20px 24px;border-bottom:1px solid var(--edge);display:flex;justify-content:space-between;gap:16px;align-items:center}h1{font-size:21px;margin:0}h2{font-size:15px;margin:0 0 12px}.muted{color:var(--muted)}.badge{color:var(--amber);border:1px solid #765829;background:#2b2315;padding:6px 10px;border-radius:6px;font-weight:700}nav{display:flex;gap:8px;padding:12px 24px;border-bottom:1px solid var(--edge);flex-wrap:wrap}nav a{color:var(--muted);text-decoration:none;padding:8px 12px;border-radius:6px}nav a.on,nav a:hover{background:#1d304a;color:var(--text)}main{padding:20px 24px;max-width:1800px;margin:auto}.grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(300px,1fr);gap:16px}.panel{background:var(--panel);border:1px solid var(--edge);border-radius:10px;padding:16px;margin-bottom:16px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.card{background:#172537;border:1px solid var(--edge);border-radius:8px;padding:12px}.card strong{display:block;font-size:19px;margin-top:5px}.ok{color:var(--green)}.bad{color:var(--red)}.hold{color:var(--blue)}.pill{font-weight:700;border-radius:5px;background:#192f45;padding:3px 7px;display:inline-block}.kv{display:grid;grid-template-columns:1fr 1fr;gap:8px}.kv div{padding:5px 0;border-bottom:1px solid #213149}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border-bottom:1px solid var(--edge);padding:8px;text-align:left;white-space:nowrap}th{color:var(--muted);cursor:pointer}tbody tr:hover,tbody tr.sel{background:#1b2b40;cursor:pointer}.scroll{overflow:auto;max-height:420px}.chart-scroll{overflow:auto;background:#0c1725;border:1px solid var(--edge);border-radius:6px}svg{display:block}select,input,button{background:#172537;color:var(--text);border:1px solid var(--edge);border-radius:5px;padding:8px}button{cursor:pointer}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.filters>*{max-width:180px}.state{display:grid;grid-template-columns:1fr 1fr;gap:7px}.state div{background:#172537;border-radius:5px;padding:8px}.state b{display:block;margin-top:3px}.subtabs{display:flex;gap:8px;margin-bottom:14px}.subtabs button.active{border-color:var(--blue);color:var(--blue)}.wide{overflow:auto}.note{line-height:1.5}.hide{display:none!important}@media(max-width:980px){.grid{grid-template-columns:1fr}header{display:block}header .badge{margin-top:10px;display:inline-block}}
</style></head><body><header><div><h1>DOWNSIDE MANAGER SHADOW</h1><div class="muted">Fixed +2R control · frozen downside_manager_v1 · causal M1 decisions</div></div><div class="badge">SHADOW ONLY — NO BROKER EXECUTION</div></header>
<nav><a href="/downside-shadow" data-nav="live">Live Shadow</a><a href="/downside-shadow/trades" data-nav="history">Trade History</a><a href="/downside-shadow/real-replays" data-nav="replays">Real Trade Replays</a><a href="/downside-shadow/metrics" data-nav="metrics">Metrics</a></nav><main><div id="message" class="muted"></div>
<section id="metrics" class="hide"><div id="sample" class="badge"></div><div class="filters"><select id="group"><option value="all">All replayable</option><option value="strategy">Group by strategy</option><option value="session">Group by session</option><option value="month">Group by month</option></select></div><div id="metric-groups"></div></section>
<section id="history" class="hide"><div class="panel"><h2>SHADOW / REAL TRADE HISTORY</h2><div class="filters"><select id="fstrategy"><option value="">All strategies</option></select><select id="fsession"><option value="">All sessions</option></select><select id="fside"><option value="">Both sides</option><option>LONG</option><option>SHORT</option></select><select id="fresult"><option value="">All results</option><option value="winner">Fixed +2R winner</option><option value="loser">Fixed +2R loser</option><option value="improved">Manager improved</option><option value="damaged">Manager damaged</option><option value="unreplayable">Unreplayable</option></select><input type="date" id="fstart"><input type="date" id="fend"></div><div class="scroll"><table><thead><tr><th data-sort="time_et">Date</th><th data-sort="strategy">Strategy</th><th data-sort="session">Session</th><th data-sort="side">Side</th><th data-sort="entry">Entry</th><th data-sort="control_r">Fixed2R R</th><th data-sort="manager_r">Manager R</th><th data-sort="delta_r">Delta R</th><th>Manager decision</th><th data-sort="status">Result</th></tr></thead><tbody id="history-body"></tbody></table></div></div></section>
<section id="live" class="hide"><div class="panel"><h2>LIVE SHADOW</h2><div class="muted" id="live-status">Loading…</div><div class="scroll"><table><thead><tr><th>Trade</th><th>Strategy</th><th>Side</th><th>Entry</th><th>Status</th><th>Current R</th><th>Recommendation</th></tr></thead><tbody id="live-body"></tbody></table></div></div></section>
<section id="detail" class="hide"><div class="panel"><div class="subtabs"><button id="back">← Back to list</button><button id="refresh">Refresh</button></div><h2 id="trade-title">Trade</h2><div id="trade-header" class="cards"></div></div><div class="grid"><div><div class="panel"><h2>M1 Candles &amp; Virtual Decisions</h2><div class="chart-scroll" id="chart"></div><div class="muted">Markers show the decision made from previously closed candles. Stop has priority over target on an ambiguous M1 bar.</div></div><div class="panel"><h2>Decision Log</h2><div class="scroll"><table><thead><tr><th>Time</th><th>Price</th><th>R</th><th>Probability</th><th>MFE</th><th>Giveback</th><th>Context</th><th>Decision</th></tr></thead><tbody id="decision-body"></tbody></table></div></div></div><div><div class="panel"><h2>MANAGER STATE</h2><div class="muted">Select a decision marker or log row</div><div id="state" class="state"></div></div><div class="panel"><h2>Outcome comparison</h2><div id="outcomes"></div></div></div></div></section>
</main><script>
const $=id=>document.getElementById(id),fmt=(x,n=2)=>x==null?'—':Number(x).toFixed(n),money=x=>x==null?'—':('$'+Number(x).toFixed(2)),date=ms=>ms==null?'—':new Date(ms).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),cls=x=>x>1e-9?'ok':x<-1e-9?'bad':'muted';
let catalog=[],summary={},selected=null,mode='history',sortKey='time_et',sortAsc=false,liveRows=[];
function setMode(m){mode=m;for(const id of ['metrics','history','live','detail'])$(id).classList.toggle('hide',id!==m);document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('on',a.dataset.nav===m));}
async function api(url){let r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function card(label,value){return `<div class="card"><span class="muted">${esc(label)}</span><strong>${value}</strong></div>`}
function metrics(rows){let a=rows.filter(x=>x.status==='REPLAYED').sort((x,y)=>x.fill_ms-y.fill_ms||String(x.id).localeCompare(String(y.id))),base=a.map(x=>x.control_r),mgr=a.map(x=>x.manager_r);function one(v){let w=v.filter(x=>x>0),l=v.filter(x=>x<0),peak=0,cur=0,dd=0;v.forEach(x=>{cur+=x;peak=Math.max(peak,cur);dd=Math.max(dd,peak-cur)});return {trades:v.length,wr:v.length?100*w.length/v.length:null,pf:l.length?w.reduce((a,b)=>a+b,0)/-l.reduce((a,b)=>a+b,0):null,net:v.reduce((a,b)=>a+b,0),dd}}let b=one(base),m=one(mgr);return `<div class="cards">${card('Fixed +2R · trades',b.trades)}${card('Fixed +2R · WR',fmt(b.wr,1)+'%')}${card('Fixed +2R · PF',fmt(b.pf))}${card('Fixed +2R · Net R',`<span class="${cls(b.net)}">${fmt(b.net)}R</span>`)}${card('Fixed +2R · Max DD',fmt(b.dd)+'R')}${card('Manager · trades',m.trades)}${card('Manager · WR',fmt(m.wr,1)+'%')}${card('Manager · PF',fmt(m.pf))}${card('Manager · Net R',`<span class="${cls(m.net)}">${fmt(m.net)}R</span>`)}${card('Manager · Max DD',fmt(m.dd)+'R')}${card('Delta R',`<span class="${cls(m.net-b.net)}">${fmt(m.net-b.net)}R</span>`)}${card('Losers improved',a.filter(x=>x.control_r<0&&x.manager_r>x.control_r+1e-9).length)}${card('Winners damaged',a.filter(x=>x.control_r>0&&x.manager_r<x.control_r-1e-9).length)}${card('Winner preservation',fmt(100*a.filter(x=>x.control_r>0&&x.manager_r>0).length/Math.max(1,a.filter(x=>x.control_r>0).length),1)+'%')}${card('Avg original loser · before',fmt(a.filter(x=>x.control_r<0).reduce((s,x)=>s+x.control_r,0)/Math.max(1,a.filter(x=>x.control_r<0).length))+'R')}${card('Avg original loser · after',fmt(a.filter(x=>x.control_r<0).reduce((s,x)=>s+x.manager_r,0)/Math.max(1,a.filter(x=>x.control_r<0).length))+'R')}</div>`}
function renderMetrics(){let how=$('group').value,valid=catalog.filter(x=>x.status==='REPLAYED');let groups={};if(how==='all')groups['All recent real trades']=valid;else valid.forEach(x=>{let k=how==='month'?x.time_et.slice(0,7):x[how]||'Unknown';(groups[k]??=[]).push(x)});$('metric-groups').innerHTML=Object.entries(groups).map(([k,v])=>`<div class="panel"><h2>${esc(k)}</h2>${metrics(v)}</div>`).join('')||'<p>No replayable trades.</p>';}
function filters(){let a=catalog.filter(x=>!$('fstrategy').value||x.strategy===$('fstrategy').value).filter(x=>!$('fsession').value||x.session===$('fsession').value).filter(x=>!$('fside').value||x.side===$('fside').value).filter(x=>!$('fstart').value||x.time_et.slice(0,10)>=$('fstart').value).filter(x=>!$('fend').value||x.time_et.slice(0,10)<=$('fend').value);let f=$('fresult').value;if(f)a=a.filter(x=>f==='unreplayable'?x.status!=='REPLAYED':x.status==='REPLAYED'&&(f==='winner'?x.control_r>0:f==='loser'?x.control_r<0:f==='improved'?x.delta_r>1e-9:x.delta_r<-1e-9));a.sort((x,y)=>{let p=x[sortKey],q=y[sortKey];return (p==null?1:q==null?-1:typeof p==='number'?p-q:String(p).localeCompare(String(q)))*(sortAsc?1:-1)});return a}
function renderHistory(){let a=filters();$('history-body').innerHTML=a.map(x=>`<tr data-id="${esc(x.id)}"><td>${esc(x.time_et)}</td><td>${esc(x.strategy)}</td><td>${esc(x.session)}</td><td>${esc(x.side)}</td><td>${fmt(x.entry??x.listed_entry)}</td><td>${fmt(x.control_r)}</td><td>${fmt(x.manager_r)}</td><td class="${cls(x.delta_r)}">${fmt(x.delta_r)}</td><td>${esc(x.last_decision||'—')}</td><td>${esc(x.status==='REPLAYED'?'REPLAYED':x.reason||x.status)}</td></tr>`).join('');$('history-body').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>location.href='/downside-shadow/trade/'+encodeURIComponent(tr.dataset.id));}
function context(d){let m=d.m1||{},z=d.dol||{};return [m.structure_relative>0?'M1 favorable':m.structure_relative<0?'M1 opposite':'M1 neutral',m.opposite_break?'opposite MSS/BOS':null,m.fvg_hold_valid==null?'FVG unknown':m.fvg_hold_valid?'FVG holds':'FVG failed',z.execution_status?'execution '+z.execution_status:null,z.htf_status?'HTF '+z.htf_status:null].filter(Boolean).join(' · ')}
function state(d){if(!d){$('state').innerHTML='';return}let m=d.m1||{},z=d.dol||{},items=[['Current R',fmt(d.current_r)+'R'],['MFE',fmt(d.mfe_r)+'R'],['MAE',fmt(d.mae_r)+'R'],['Giveback',fmt(d.giveback_r)+'R'],['M1 structure',m.structure_relative>0?'Favorable':m.structure_relative<0?'Opposite':'Neutral'],['Opposite MSS/BOS',m.opposite_break?'YES':'NO'],['FVG',m.fvg_hold_valid==null?'Unknown':m.fvg_hold_valid?'Holds':'Failed'],['Execution DOL',(z.execution_status||'Unknown')+' · '+fmt(z.execution_price)],['HTF DOL',(z.htf_status||'Unknown')+' · '+fmt(z.htf_price)],['Momentum 1/3/5',`${fmt(m.return_1_r)} / ${fmt(m.return_3_r)} / ${fmt(m.return_5_r)}`],['Protected swing',fmt(m.protected_price)],['Session left',fmt(d.session_remaining_minutes,0)+' min'],['Probability',fmt(d.probability,4)],['Threshold',fmt(d.threshold,4)],['Recommendation',`<span class="${d.recommendation==='HOLD'?'hold':d.recommendation==='HOLD_ENTRY'?'hold':'ok'}">${esc(d.recommendation)}</span>`]];$('state').innerHTML=items.map(([k,v])=>`<div><span class="muted">${k}</span><b>${v}</b></div>`).join('')}
function chart(trade){let detail=trade.detail;if(!detail){$('chart').textContent='No filled path yet.';return}let candles=detail.candles||[];if(!candles.length){$('chart').textContent='No M1 candles.';return}let levels=[trade.entry,trade.initial_sl,trade.fixed_tp,...detail.manager.decisions.map(x=>x.virtual_sl_after_action)].filter(x=>x!=null),hi=Math.max(...candles.map(x=>x[2]),...levels)+2,lo=Math.min(...candles.map(x=>x[3]),...levels)-2,w=Math.max(800,candles.length*11+80),h=350,left=42,top=18,plotH=h-55,xx=i=>left+i*11+5,yy=p=>top+(hi-p)/(hi-lo)*plotH;let lines=[[trade.entry,'#69aaff','ENTRY'],[trade.initial_sl,'#ff7287','INITIAL SL'],[trade.fixed_tp,'#40d69a','FIXED +2R']];let last=detail.manager.decisions.at(-1);if(last&&last.virtual_sl_after_action!==trade.initial_sl)lines.push([last.virtual_sl_after_action,'#ffc66d','MANAGER SL']);let latestDol=last?.dol||{};if(latestDol.execution_price!=null)lines.push([latestDol.execution_price,'#b796ff','EXEC DOL']);if(latestDol.htf_price!=null)lines.push([latestDol.htf_price,'#66d9e8','HTF DOL']);let svg=`<svg viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" role="img" aria-label="M1 candlestick trade replay"><rect width="${w}" height="${h}" fill="#0c1725"/>`;for(let [p,color,label] of lines)svg+=`<line x1="${left}" x2="${w-3}" y1="${yy(p)}" y2="${yy(p)}" stroke="${color}" stroke-dasharray="5 4" opacity=".7"/><text x="3" y="${yy(p)-3}" fill="${color}" font-size="9">${label}</text>`;candles.forEach((b,i)=>{let color=b[4]>=b[1]?'#40d69a':'#ff7287',x=xx(i),body=Math.max(1,Math.abs(yy(b[1])-yy(b[4])));svg+=`<line x1="${x}" x2="${x}" y1="${yy(b[2])}" y2="${yy(b[3])}" stroke="${color}"/><rect x="${x-3}" y="${Math.min(yy(b[1]),yy(b[4]))}" width="6" height="${body}" fill="${color}" opacity=".85"><title>${date(b[0])} O ${b[1]} H ${b[2]} L ${b[3]} C ${b[4]}</title></rect>`});detail.manager.decisions.forEach((d,j)=>{let i=Math.round((d.decision_ms-candles[0][0])/60000),x=xx(Math.max(0,Math.min(candles.length-1,i))),y=yy(d.price),label=d.recommendation,color=label==='HOLD'||label==='HOLD_ENTRY'?'#69aaff':label==='BE'?'#ffc66d':label==='PROTECTED_STOP'?'#40d69a':'#ff7287';svg+=`<circle data-decision="${j}" cx="${x}" cy="${y}" r="${label.startsWith('HOLD')?3:5}" fill="${color}" stroke="#07111e"><title>${date(d.decision_ms)} ${esc(label)} p=${fmt(d.probability,3)} R=${fmt(d.current_r)}</title></circle>`});let exit=detail.manager;if(exit.exit_ms!=null)svg+=`<text x="${xx(Math.max(0,Math.min(candles.length-1,Math.round((exit.exit_ms-candles[0][0])/60000))))}" y="${h-18}" fill="#ffc66d" font-size="11">${esc(exit.exit_reason||'EXIT')} ↓</text>`;svg+='</svg>';$('chart').innerHTML=svg;$('chart').querySelectorAll('[data-decision]').forEach(el=>el.onclick=()=>state(detail.manager.decisions[+el.dataset.decision]));}
function outcomes(t){let d=t.detail;if(!d){$('outcomes').textContent=t.reason||'Waiting for fill.';return}let a=t.actual_broker_usd,blocks=[['ACTUAL',a==null?'Broker P&L unavailable':money(a),'Recorded broker P&L; no R comparison without reconciled fill'],['FIXED +2R',fmt(d.control.final_r)+'R',`${d.control.exit_reason||'OPEN'} · ${date(d.control.exit_ms)}`],['MANAGER',fmt(d.manager.final_r)+'R',`${d.manager.exit_reason||'OPEN'} · ${date(d.manager.exit_ms)}`]];$('outcomes').innerHTML=blocks.map(([k,v,n])=>`<div class="card" style="margin-bottom:8px"><span class="muted">${k}</span><strong>${v}</strong><span class="muted">${esc(n)}</span></div>`).join('')+`<div class="card"><span class="muted">MANAGER DELTA VS FIXED2R</span><strong class="${cls(d.delta_r)}">${d.delta_r==null?'Open':(d.delta_r>=0?'+':'')+fmt(d.delta_r)+'R'}</strong></div>`}
function detail(t){selected=t;setMode('detail');$('trade-title').textContent=(t.strategy||t.strategy_id||'Trade')+' · '+(t.time_et||date(t.fill_ms));$('trade-header').innerHTML=[['Strategy',t.strategy||t.strategy_id],['Session',t.session||'—'],['Side',t.side],['Entry',fmt(t.entry)],['Initial SL',fmt(t.initial_sl)],['Fixed +2R',fmt(t.fixed_tp)],['Quantity',t.quantity],['Shadow status',t.status],['State quality',t.state_quality||'Historical causal replay']].map(([k,v])=>card(k,esc(v))).join('');chart(t);outcomes(t);let decisions=t.detail?.manager.decisions||[];$('decision-body').innerHTML=decisions.map((d,j)=>`<tr data-decision="${j}"><td>${date(d.decision_ms)}</td><td>${fmt(d.price)}</td><td>${fmt(d.current_r)}</td><td>${fmt(d.probability,3)}</td><td>${fmt(d.mfe_r)}</td><td>${fmt(d.giveback_r)}</td><td>${esc(context(d))}</td><td><span class="pill">${esc(d.recommendation)}</span></td></tr>`).join('');$('decision-body').querySelectorAll('tr').forEach(el=>el.onclick=()=>state(decisions[+el.dataset.decision]));state(decisions.at(-1));}
async function loadLive(){let x=await api('/downside-shadow/api/live');liveRows=x.trades||[];$('live-status').textContent=`${x.status.enabled?'ENABLED':'DISABLED'} · ${x.status.open||0} open · ${x.status.done||0} done · C not connected`; $('live-body').innerHTML=liveRows.map(x=>`<tr data-id="${x.id}"><td>${esc(x.source_key)}</td><td>${esc(x.strategy_id)}</td><td>${x.direction===1?'LONG':'SHORT'}</td><td>${fmt(x.entry)}</td><td>${esc(x.status)}</td><td>${fmt(x.current_r)}</td><td>${esc(x.recommendation||'—')}</td></tr>`).join('');$('live-body').querySelectorAll('tr').forEach(el=>el.onclick=async()=>detail(await api('/downside-shadow/api/live/'+el.dataset.id)));}
async function init(){try{let x=await api('/downside-shadow/api/trades');catalog=x.trades||[];summary=x.summary||{};$('sample').textContent=summary.sample_label||'Recent sample — descriptive only';for(let [id,key] of [['fstrategy','strategy'],['fsession','session']]){let s=$(''+id);[...new Set(catalog.map(x=>x[key]))].sort().forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;s.append(o)})}['fstrategy','fsession','fside','fresult','fstart','fend'].forEach(id=>$(id).onchange=renderHistory);$('group').onchange=renderMetrics;document.querySelectorAll('[data-sort]').forEach(el=>el.onclick=()=>{sortAsc=sortKey===el.dataset.sort?!sortAsc:true;sortKey=el.dataset.sort;renderHistory()});$('back').onclick=()=>{history.pushState(null,'','/downside-shadow/trades');setMode('history');renderHistory()};$('refresh').onclick=()=>location.reload();renderHistory();renderMetrics();let p=location.pathname;if(p.startsWith('/downside-shadow/trade/')){let id=decodeURIComponent(p.slice('/downside-shadow/trade/'.length));detail(await api('/downside-shadow/api/trade/'+encodeURIComponent(id)))}else if(p.endsWith('/metrics'))setMode('metrics');else if(p.endsWith('/real-replays')||p.endsWith('/trades'))setMode('history');else{setMode('live');await loadLive()}}catch(e){$('message').textContent='Dashboard data error: '+e.message}}
init();
</script></body></html>'''
