-- Shadow-only persistence. No canonical or broker tables are changed.
CREATE TABLE IF NOT EXISTS downside_shadow_trades (
    id INTEGER PRIMARY KEY,
    source_key TEXT NOT NULL,
    trade_id TEXT NOT NULL,
    strategy_id TEXT NOT NULL,
    signal_json TEXT NOT NULL,
    direction INTEGER NOT NULL CHECK(direction IN (-1,1)),
    entry REAL NOT NULL,
    initial_sl REAL NOT NULL,
    fixed_tp REAL NOT NULL,
    quantity INTEGER NOT NULL CHECK(quantity >= 1),
    initial_risk REAL NOT NULL CHECK(initial_risk > 0),
    signal_ms INTEGER NOT NULL,
    entry_anchor_ms INTEGER NOT NULL,
    fill_ms INTEGER,
    status TEXT NOT NULL DEFAULT 'PENDING',
    control_status TEXT NOT NULL DEFAULT 'PENDING',
    manager_status TEXT NOT NULL DEFAULT 'PENDING',
    last_bar_ms INTEGER,
    pre_bars_json TEXT NOT NULL DEFAULT '[]',
    bars_json TEXT NOT NULL DEFAULT '[]',
    dol_states_json TEXT NOT NULL DEFAULT '[]',
    state_quality TEXT NOT NULL DEFAULT 'PENDING',
    control_virtual_sl REAL,
    manager_virtual_sl REAL,
    current_r REAL,
    mfe_r REAL,
    mae_r REAL,
    dol_state_json TEXT,
    m1_state_json TEXT,
    manager_probability REAL,
    recommendation TEXT,
    control_final_r REAL,
    manager_final_r REAL,
    delta_r REAL,
    control_exit_reason TEXT,
    manager_exit_reason TEXT,
    model_hash TEXT NOT NULL,
    threshold REAL NOT NULL,
    policy_version TEXT NOT NULL,
    feature_schema_version TEXT NOT NULL,
    dol_runtime_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(strategy_id, source_key),
    UNIQUE(trade_id)
);
CREATE INDEX IF NOT EXISTS idx_downside_shadow_status ON downside_shadow_trades(status, last_bar_ms);
CREATE INDEX IF NOT EXISTS idx_downside_shadow_strategy ON downside_shadow_trades(strategy_id, fill_ms);

CREATE TABLE IF NOT EXISTS downside_shadow_decisions (
    id INTEGER PRIMARY KEY,
    trade_fk INTEGER NOT NULL REFERENCES downside_shadow_trades(id),
    decision_ms INTEGER NOT NULL,
    control_status TEXT NOT NULL,
    manager_status TEXT NOT NULL,
    current_r REAL,
    mfe_r REAL,
    mae_r REAL,
    control_virtual_sl REAL,
    manager_virtual_sl REAL,
    manager_probability REAL,
    recommendation TEXT NOT NULL,
    dol_state_json TEXT,
    m1_state_json TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(trade_fk, decision_ms)
);
CREATE INDEX IF NOT EXISTS idx_downside_shadow_decision_time ON downside_shadow_decisions(decision_ms);
